# Generated by Django 5.1.5 on 2025-02-13 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='rol',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
