# Generated by Django 5.1.6 on 2025-03-22 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0002_usuarios_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registros',
            name='fecha',
            field=models.DateTimeField(),
        ),
    ]
